version: '3.8'

services:

  db:
    image: postgres
    container_name: socialapp-db
    restart: always
    environment:
      POSTGRES_PASSWORD: 
      POSTGRES_DB: socialapp
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  mongo:
    container_name: socialapp-mongo
    restart: always
    image: mongo
    ports:
      - "27017"
    volumes:
      - mongodata:/data/db

  backend:
    build: ./server
    container_name: socialapp-backend
    restart: always
    ports:
      - "5000:5000"
      - "7000:7000"
      - "9000:9000"
    environment:
      - NODE_ENV=docker
    depends_on:
      - db
      - mongo
    volumes:
      - uploads:/app/uploads

  frontend:
    build: ./client
    container_name: socialapp-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  dbdata:
  mongodata:
  uploads:

