version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
      - "7000:7000"
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:123456d@db:5432/socialapp
      - MONGO_URL=mongodb://mongo:27017/rooms
    depends_on:
      - db
      - mongo
    volumes:
      - uploads:/app/uploads

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: socialapp
    ports:
      - "5432:5432"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  uploads:
  mongo-data:
  pgadmin-data:

